### PR TITLE
fix: correct default home path

### LINKED ISSUE #1683: icq: default config is written to wrong location
## Summary of Bug

Config is loaded from the literal path '~'/.icq, instead of being expanded to /home/$USER/.icq - missing os.expandPath() somewhere? 
## Expected Behaviour

Config is loaded and written to relative to user home directory, not a directory named "~" inside the cwd.

## Version

f35b3c1d3cb72d875a3d984c02d45a71a76e41ce

## Steps to Reproduce

```
make build
./icq-relayer start <key>
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

### PR DESCRIPTION
**Pull request by hoank101**
## 1. Summary
Fixes #1683 

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 5. Checklist

- [ ] Does the Readme need to be updated?

### CODE REVIEW

File: icq-relayer/cmd/root.go [hunk 1]
```diff
@@ -21,13 +22,17 @@ import (
...
 )
 
 // Execute adds all child commands to the root command and sets flags appropriately.
 // This is called by main.main(). It only needs to happen once to the rootCmd.
 func Execute() {
+	userHomeDir, err := os.UserHomeDir()
+	if err != nil {
+		panic(err)
+	}
+	defaultHome := filepath.Join(userHomeDir, ".icq")
```
Comment (odeke-em) [inline icq-relayer/cmd/root.go:35]: Let's not duplicate this functionality everywhere, let's extract this code into a helper

```go
var homeDirOnce sync.Once
var defaultHome string

func retrieveHomeDir() {
    homeDirOnce.Do(func() {
        userHomeDir, err := os.UserHomeDir()
        if err != nil {
            panic(err)
        }
        defaultHome = filepath.Join(userHomeDir, ".icq")
    })
    return defaultHome
}
```

and then use it allover instead of that duplication in icq-relayer/cmd/run.go

Comment (hoank101) [reply icq-relayer/cmd/root.go]: thank you

**Review by tropicaldog — APPROVED** [review]

**Review by odeke-em — APPROVED** [review]
Thank you @hoank101! This will work, although I had suggested using sync.Once
```go
var homeDirOnce sync.Once
var defaultHome string

func retrieveHomeDir() {
    homeDirOnce.Do(func() {
        userHomeDir, err := os.UserHomeDir()
        if err != nil {
            panic(err)
        }
        defaultHome = filepath.Join(userHomeDir, ".icq")
    })
    return defaultHome
}
```

**Comment by odeke-em** [comment]
Kind ping @faddat @joe-bowman, this PR has been ready for more than 2 weeks. Thank you.

**Comment by joe-bowman** [comment]
This pull request has been automatically marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. Thank you!
